mklive.sh: first steps for limine [wip]

diff --git a/mklive.sh.in b/mklive.sh.in
--- a/mklive.sh.in
+++ b/mklive.sh.in
@@ -145,10 +145,10 @@ install_packages() {
 enable_services() {
     SERVICE_LIST="$*"
     for service in $SERVICE_LIST; do
-        if ! [ -e $ROOTFS/etc/sv/$service ]; then
+        if ! [ -e "$ROOTFS"/etc/sv/"$service" ]; then
             die "service $service not in /etc/sv"
         fi
-        ln -sf /etc/sv/$service $ROOTFS/etc/runit/runsvdir/default/
+        ln -sf /etc/sv/"$service" "$ROOTFS"/etc/runit/runsvdir/default/
     done
 }
 
@@ -182,77 +182,31 @@ cleanup_rootfs() {
     rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01autoinstaller
 }
 
-generate_isolinux_boot() {
-    cp -f "$SYSLINUX_DATADIR"/isolinux.bin "$ISOLINUX_DIR"
-    cp -f "$SYSLINUX_DATADIR"/ldlinux.c32 "$ISOLINUX_DIR"
-    cp -f "$SYSLINUX_DATADIR"/libcom32.c32 "$ISOLINUX_DIR"
-    cp -f "$SYSLINUX_DATADIR"/vesamenu.c32 "$ISOLINUX_DIR"
-    cp -f "$SYSLINUX_DATADIR"/libutil.c32 "$ISOLINUX_DIR"
-    cp -f "$SYSLINUX_DATADIR"/chain.c32 "$ISOLINUX_DIR"
-    cp -f isolinux/isolinux.cfg.in "$ISOLINUX_DIR"/isolinux.cfg
-    cp -f ${SPLASH_IMAGE} "$ISOLINUX_DIR"
 
-    sed -i  -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
-        -e "s|@@KERNVER@@|${KERNELVERSION}|" \
-        -e "s|@@KEYMAP@@|${KEYMAP}|" \
-        -e "s|@@ARCH@@|$BASE_ARCH|" \
-        -e "s|@@LOCALE@@|${LOCALE}|" \
-        -e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
-        -e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
-        "$ISOLINUX_DIR"/isolinux.cfg
+generate_limine_boot() {
+# Just following upstream documentation, needs testing and refinement
+
+    cp -f "$LIMINE_DATADIR"/limine-cd-efi.bin "$LIMINE_DIR"
+    cp -f "$LIMINE_DATADIR"/limine-cd.bin "$LIMINE_DIR"
+    cp -f "$LIMINE_DATADIR"/limine.sys "$LIMINE_DIR"
+    cp -f "$LIMINE_DATADIR"/limine.cfg "$LIMINE_DIR"
+#    cp -f "$SYSLINUX_DATADIR"/libutil.c32 "$ISOLINUX_DIR"
+#    cp -f "$SYSLINUX_DATADIR"/chain.c32 "$ISOLINUX_DIR"
+#    cp -f isolinux/isolinux.cfg.in "$ISOLINUX_DIR"/isolinux.cfg
+#    cp -f ${SPLASH_IMAGE} "$ISOLINUX_DIR"
+
+# That will require some testing with limine.cfg.
+
+#    sed -i  -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
+#        -e "s|@@KERNVER@@|${KERNELVERSION}|" \
+#        -e "s|@@KEYMAP@@|${KEYMAP}|" \
+#        -e "s|@@ARCH@@|$BASE_ARCH|" \
+#        -e "s|@@LOCALE@@|${LOCALE}|" \
+#        -e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
+#        -e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
+#        "$ISOLINUX_DIR"/isolinux.cfg
 }
 
-generate_grub_efi_boot() {
-    cp -f grub/grub.cfg "$GRUB_DIR"
-    cp -f grub/grub_void.cfg.in "$GRUB_DIR"/grub_void.cfg
-    sed -i  -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
-        -e "s|@@KERNVER@@|${KERNELVERSION}|" \
-        -e "s|@@KEYMAP@@|${KEYMAP}|" \
-        -e "s|@@ARCH@@|$BASE_ARCH|" \
-        -e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
-        -e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
-        -e "s|@@LOCALE@@|${LOCALE}|" "$GRUB_DIR"/grub_void.cfg
-    mkdir -p "$GRUB_DIR"/fonts
-    cp -f "$GRUB_DATADIR"/unicode.pf2 "$GRUB_DIR"/fonts
-
-    modprobe -q loop || :
-
-    # Create EFI vfat image.
-    truncate -s 32M "$GRUB_DIR"/efiboot.img >/dev/null 2>&1
-    mkfs.vfat -F12 -S 512 -n "grub_uefi" "$GRUB_DIR/efiboot.img" >/dev/null 2>&1
-
-    GRUB_EFI_TMPDIR="$(mktemp --tmpdir="$HOME" -d)"
-    LOOP_DEVICE="$(losetup --show --find "${GRUB_DIR}"/efiboot.img)"
-    mount -o rw,flush -t vfat "${LOOP_DEVICE}" "${GRUB_EFI_TMPDIR}" >/dev/null 2>&1
-
-    cp -a "$IMAGEDIR"/boot "$VOIDHOSTDIR"
-    xbps-uchroot "$VOIDHOSTDIR" grub-mkstandalone -- \
-		 --directory="/usr/lib/grub/i386-efi" \
-		 --format="i386-efi" \
-		 --output="/tmp/bootia32.efi" \
-		 "boot/grub/grub.cfg"
-    if [ $? -ne 0 ]; then
-        umount "$GRUB_EFI_TMPDIR"
-        losetup --detach "${LOOP_DEVICE}"
-        die "Failed to generate EFI loader"
-    fi
-    mkdir -p "${GRUB_EFI_TMPDIR}"/EFI/BOOT
-    cp -f "$VOIDHOSTDIR"/tmp/bootia32.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTIA32.EFI
-    xbps-uchroot "$VOIDHOSTDIR" grub-mkstandalone -- \
-		 --directory="/usr/lib/grub/x86_64-efi" \
-		 --format="x86_64-efi" \
-		 --output="/tmp/bootx64.efi" \
-		 "boot/grub/grub.cfg"
-    if [ $? -ne 0 ]; then
-        umount "$GRUB_EFI_TMPDIR"
-        losetup --detach "${LOOP_DEVICE}"
-        die "Failed to generate EFI loader"
-    fi
-    cp -f "$VOIDHOSTDIR"/tmp/bootx64.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTX64.EFI
-    umount "$GRUB_EFI_TMPDIR"
-    losetup --detach "${LOOP_DEVICE}"
-    rm -rf "$GRUB_EFI_TMPDIR"
-}
 
 generate_squashfs() {
     umount_pseudofs
@@ -267,19 +221,24 @@ generate_squashfs() {
     rm -rf "$ROOTFS" "$BUILDDIR/tmp-rootfs" "$BUILDDIR/tmp"
 }
 
+
 generate_iso_image() {
-    "$VOIDHOSTDIR"/usr/bin/xorriso -as mkisofs \
-        -iso-level 3 -rock -joliet \
+# Just following the upstream documentation, needs testing and refinement.
+	"$VOIDHOSTDIR"/usr/bin/xorriso -as mkisofs \
+		-iso-level 3 -rock -joliet \
         -max-iso9660-filenames -omit-period \
         -omit-version-number -relaxed-filenames -allow-lowercase \
         -volid "VOID_LIVE" \
-        -eltorito-boot boot/isolinux/isolinux.bin \
-        -eltorito-catalog boot/isolinux/boot.cat \
+        -b boot/limine-cd.bin \
         -no-emul-boot -boot-load-size 4 -boot-info-table \
-        -eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot \
-        -isohybrid-mbr "$SYSLINUX_DATADIR"/isohdpfx.bin \
-        -output "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"
+        --efi-boot boot/limine-cd-efi.bin \
+        -efi-boot-part --efi-boot-image --protective-msdos-label \
+        "$ROOTFS" -o "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"
+	
+	# Install the bootloader
+	"$VOIDHOSTDIR"/usr/bin/limine-deploy "$IMAGEDIR/$OUTPUT_FILE"|| die "Failed to install bootloader"
 }
+
 
 #
 # main()
@@ -342,15 +301,13 @@ IMAGEDIR="$BUILDDIR/image"
 ROOTFS="$IMAGEDIR/rootfs"
 VOIDHOSTDIR="$BUILDDIR/void-host"
 BOOT_DIR="$IMAGEDIR/boot"
-ISOLINUX_DIR="$BOOT_DIR/isolinux"
-GRUB_DIR="$BOOT_DIR/grub"
-#ISOLINUX_CFG="$ISOLINUX_DIR/isolinux.cfg"
+LIMINE_DIR="$BOOT_DIR/limine"
 CURRENT_STEP=0
-STEP_COUNT=9
+STEP_COUNT=8
 [ -n "${INCLUDE_DIRECTORY}" ] && STEP_COUNT=$((STEP_COUNT+1))
 
-: ${SYSLINUX_DATADIR:="$VOIDHOSTDIR"/usr/lib/syslinux}
-: ${GRUB_DATADIR:="$VOIDHOSTDIR"/usr/share/grub}
+# Chnage for the real dir.
+: ${LIMINE_DATADIR:="$VOIDHOSTDIR"/usr/lib/syslinux}
 : ${SPLASH_IMAGE:=data/splash.png}
 : ${XBPS_INSTALL_CMD:=xbps-install}
 : ${XBPS_REMOVE_CMD:=xbps-remove}
@@ -411,11 +368,8 @@ fi
 print_step "Generating initramfs image ($INITRAMFS_COMPRESSION)..."
 generate_initramfs
 
-print_step "Generating isolinux support for PC-BIOS systems..."
-generate_isolinux_boot
-
-print_step "Generating GRUB support for EFI systems..."
-generate_grub_efi_boot
+print_step "Generating limine bootloader support ..."
+generate_limine_boot
 
 print_step "Cleaning up rootfs..."
 cleanup_rootfs
